# Marker genes configuration file for tissue-specific decontamination
# This file defines known markers for different cell types and tissues

# General markers that can be used across tissues
known_markers:
  - "ENSG00000081237"  # PTPRC (CD45 - immune cells)
  - "ENSG00000110799"  # VWF (von Willebrand factor - endothelial cells)
  # Add more general markers as needed

cell_type_markers:
  # Skin tissue markers
  skin:
    # EPIDERMIS - Stratified squamous epithelium
    keratinocytes_basal:
      - "ENSG00000186081"  # KRT5 (Keratin 5)
    
    keratinocytes_cornified:
      - "ENSG00000163207"  # IVL (Involucrin)
    
    melanocytes:
      - "ENSG00000077498 "  # TYR (Tyrosinase)
    
    langerhans_cells:
      - "ENSG00000116031"  # CD207 (Langerin)
    
    fibroblasts:
      - "ENSG00000108821"  # COL1A1 (Collagen type I alpha 1)

  pancreatic_islet:
    beta_cells:
      - "ENSG00000254647"  # INS (Insulin)
    alpha_cells:
      - "ENSG00000115263"  # GCG (Glucagon)
    delta_cells:
      - "ENSG00000157005"  # SST (Somatostatin)
    gamma_cells:
      - "ENSG00000108849"  # PPY (Pancreatic polypeptide)
    ductal_cells:
      - "ENSG00000171345"  # KRT19 (Keratin 19)
    acinar_cells:
      - "ENSG00000204983"  # PRSS1 (Trypsin 1)
    stellate_cells:
      - "ENSG00000143248"  # RGS5 (Regulator of G-protein signaling 5)
    other_cells:
      - "ENSG00000135094"  # SDS (Serine dehydratase)
  
  # Brain/Neural tissue markers (example)
  brain:
    neurons:
      - "ENSG00000167281"  # RBFOX3 (NeuN)
    astrocytes:
      - "ENSG00000131095"  # GFAP (Glial fibrillary acidic protein)
    oligodendrocytes:
      - "ENSG00000197971"  # MBP (Myelin basic protein)
    microglia:
      - "ENSG00000129226"  # CD68 (General monocyte)
  
  # Liver tissue markers (example)
  liver:
    hepatocytes:
      - "ENSG00000163631"  # ALB (Albumin)
    kupffer_cells:
      - "ENSG00000129226"  # CD68 (General monocyte)
  

# Default tissue type to use if not specified
default_tissue: "general"

# Configuration for general analysis (tissue-agnostic)
general:
  immune_cells:
    - "ENSG00000081237"  # PTPRC (CD45)
  endothelial_cells:
    - "ENSG00000110799"  # VWF (von Willebrand factor)
  fibroblasts:
    - "ENSG00000108821"  # COL1A1 (Collagen type I alpha 1)
